version: 1.0.{build}
clone_folder: c:\project\badrocks

cache:
    - '%LOCALAPPDATA%\Composer\files'
    - '%APPDATA%\npm-cache'
    - c:\composer\composer.phar

init:
  - cmd: >-
      SET PATH=c:\php;%PATH%

      SET COMPOSER_NO_INTERACTION=1

      SET ANSICON=121x90 (121x90)

      REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
  - cmd: >-
      mkdir c:\php && cd c:\php

      appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/cacert.pem

      appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php-7.1.3-Win32-VC14-x86.zip

      7z x php-7.1.3-Win32-VC14-x86.zip -y >nul
      
      del /Q *.zip
      
      cd ext
      
      appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php_apcu-5.1.8-7.1-ts-vc14-x86.zip
      
      7z x php_apcu-5.1.8-7.1-ts-vc14-x86.zip -y >nul
      
      del /Q *.zip
      
      cd ..
      
      copy /Y php.ini-development php.ini
      
      echo max_execution_time=1200 >> php.ini
      
      echo date.timezone="America/Los_Angeles" >> php.ini
      
      echo extension_dir=ext >> php.ini
      
      echo zend_extension=php_opcache.dll >> php.ini
      
      echo opcache.enable_cli=1 >> php.ini
      
      echo extension=php_openssl.dll >> php.ini
      
      echo extension=php_apcu.dll >> php.ini
      
      echo apc.enable_cli=1 >> php.ini
      
      echo extension=php_intl.dll >> php.ini
      
      echo extension=php_mbstring.dll >> php.ini
      
      echo extension=php_fileinfo.dll >> php.ini
      
      echo extension=php_pdo_sqlite.dll >> php.ini
      
      echo extension=php_curl.dll >> php.ini
      
      echo curl.cainfo=c:\php\cacert.pem >> php.ini
      
      cd c:\composer
      
      IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.3.0/composer.phar)
      
      php composer.phar self-update
      
      IF %APPVEYOR_REPO_BRANCH%==master (SET COMPOSER_ROOT_VERSION=dev-master) ELSE (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_BRANCH%.x-dev)
      
      cd c:\project\badrocks
      
      php c:\composer\composer.phar update --no-progress --ansi
      
      cd c:\project\badrocks\web\app\themes\spinx
      
      php c:\composer\composer.phar update --no-progress --ansi
      
      yarn install
      
      yarn build:production
      
      SET COMPOSER_ROOT_VERSION=

build_script:
  - cmd: >-
      7z a -tzip badrocks.$($env:APPVEYOR_BUILD_VERSION).zip c:\project\badrocks
      
      appveyor PushArtifact spinx-docs.$($env:APPVEYOR_BUILD_VERSION).zip