version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-jessie-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - run: composer install -n --prefer-dist
        
      # run composer for theme
      - run: cd web/app/themes/spinx && composer install -n --prefer-dist

      # node cache
      #- run: cd web/app/themes/spinx && npm install webpack --save-dev
      - run: cd web/app/themes/spinx && yarn
      - run: cd web/app/themes/spinx && yarn build:production

      #artifacts
      - run: mkdir /tmp/artifacts
      #- run: sudo apt-get install p7zip-full
      #- run: 7z a -tzip /tmp/badrock.$CIRCLE_BUILD_NUM.zip .
      - run: zip -r /tmp/artifacts/art.zip .

      - store_artifacts:
          path: /tmp/artifacts