version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: kkarczmarczyk/node-yarn:8.0-slim

    working_directory: ~/repo

    steps:
      - checkout

      # node cache
      # - run: cd web/app/themes/spinx && npm install webpack --save-dev
      - run: cd web/app/themes/spinx && yarn build:production