version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: jonbaldie/yarn

    working_directory: ~/repo

    steps:
      - checkout

      # node cache
      # - run: cd web/app/themes/spinx && npm install webpack --save-dev
      - run: cd web/app/themes/spinx && yarn build:production

      #artifacts
      - run: mkdir /tmp/artifacts
      - run: zip -r /tmp/artifacts/art.zip .

      - store_artifacts:
          path: /tmp/artifacts